[2024-06-18T15:05:08.360+0545] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-18T15:05:08.386+0545] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Backup_Database.send_mail scheduled__2024-06-18T09:10:00+00:00 [queued]>
[2024-06-18T15:05:08.395+0545] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Backup_Database.send_mail scheduled__2024-06-18T09:10:00+00:00 [queued]>
[2024-06-18T15:05:08.396+0545] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-18T15:05:08.587+0545] {taskinstance.py:2330} INFO - Executing <Task(EmailOperator): send_mail> on 2024-06-18 09:10:00+00:00
[2024-06-18T15:05:08.595+0545] {standard_task_runner.py:63} INFO - Started process 19739 to run task
[2024-06-18T15:05:08.605+0545] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Backup_Database', 'send_mail', 'scheduled__2024-06-18T09:10:00+00:00', '--job-id', '76', '--raw', '--subdir', 'DAGS_FOLDER/basic_dag.py', '--cfg-path', '/tmp/tmp17xz9zuv']
[2024-06-18T15:05:08.610+0545] {standard_task_runner.py:91} INFO - Job 76: Subtask send_mail
[2024-06-18T15:05:08.827+0545] {task_command.py:426} INFO - Running <TaskInstance: Backup_Database.send_mail scheduled__2024-06-18T09:10:00+00:00 [running]> on host manisha-Inspiron-3580
[2024-06-18T15:05:09.323+0545] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='manisha' AIRFLOW_CTX_DAG_ID='Backup_Database' AIRFLOW_CTX_TASK_ID='send_mail' AIRFLOW_CTX_EXECUTION_DATE='2024-06-18T09:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-18T09:10:00+00:00'
[2024-06-18T15:05:09.325+0545] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-18T15:05:09.381+0545] {logging_mixin.py:188} WARNING - /home/manisha/airflow_env/lib/python3.10/site-packages/airflow/utils/email.py:154 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2024-06-18T15:05:09.381+0545] {configuration.py:1050} WARNING - section/key [smtp/smtp_user] not found in config
[2024-06-18T15:05:09.382+0545] {email.py:271} INFO - Email alerting: attempt 1
[2024-06-18T15:05:09.483+0545] {email.py:282} INFO - Sent an alert email to ['manishakhadka228@gmail.com']
[2024-06-18T15:05:09.555+0545] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-18T15:05:09.591+0545] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Backup_Database, task_id=send_mail, run_id=scheduled__2024-06-18T09:10:00+00:00, execution_date=20240618T091000, start_date=20240618T092008, end_date=20240618T092009
[2024-06-18T15:05:09.781+0545] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-18T15:05:09.823+0545] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-18T15:05:09.824+0545] {local_task_job_runner.py:222} INFO - ::endgroup::
