[2024-06-18T14:33:58.097+0545] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-18T14:33:58.141+0545] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Backup_Database.backup_task manual__2024-06-18T08:47:53.502392+00:00 [queued]>
[2024-06-18T14:33:58.155+0545] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Backup_Database.backup_task manual__2024-06-18T08:47:53.502392+00:00 [queued]>
[2024-06-18T14:33:58.155+0545] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-06-18T14:33:58.399+0545] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): backup_task> on 2024-06-18 08:47:53.502392+00:00
[2024-06-18T14:33:58.406+0545] {standard_task_runner.py:63} INFO - Started process 18679 to run task
[2024-06-18T14:33:58.415+0545] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Backup_Database', 'backup_task', 'manual__2024-06-18T08:47:53.502392+00:00', '--job-id', '62', '--raw', '--subdir', 'DAGS_FOLDER/basic_dag.py', '--cfg-path', '/tmp/tmp99exrauj']
[2024-06-18T14:33:58.421+0545] {standard_task_runner.py:91} INFO - Job 62: Subtask backup_task
[2024-06-18T14:33:58.712+0545] {task_command.py:426} INFO - Running <TaskInstance: Backup_Database.backup_task manual__2024-06-18T08:47:53.502392+00:00 [running]> on host manisha-Inspiron-3580
[2024-06-18T14:33:59.201+0545] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='manisha' AIRFLOW_CTX_DAG_ID='Backup_Database' AIRFLOW_CTX_TASK_ID='backup_task' AIRFLOW_CTX_EXECUTION_DATE='2024-06-18T08:47:53.502392+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-18T08:47:53.502392+00:00'
[2024-06-18T14:33:59.203+0545] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-18T14:33:59.224+0545] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-06-18T14:33:59.225+0545] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/manisha/airflow/bashScripts/backup.sh ']
[2024-06-18T14:33:59.235+0545] {subprocess.py:86} INFO - Output:
[2024-06-18T14:33:59.241+0545] {subprocess.py:93} INFO - mysqldump: [Warning] Using a password on the command line interface can be insecure.
[2024-06-18T14:33:59.249+0545] {subprocess.py:93} INFO - mysqldump: Error: 'Access denied; you need (at least one of) the PROCESS privilege(s) for this operation' when trying to dump tablespaces
[2024-06-18T14:33:59.663+0545] {subprocess.py:97} INFO - Command exited with return code 0
[2024-06-18T14:33:59.665+0545] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-18T14:33:59.965+0545] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Backup_Database, task_id=backup_task, run_id=manual__2024-06-18T08:47:53.502392+00:00, execution_date=20240618T084753, start_date=20240618T084858, end_date=20240618T084859
[2024-06-18T14:34:00.196+0545] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-18T14:34:00.270+0545] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-18T14:34:00.470+0545] {local_task_job_runner.py:222} INFO - ::endgroup::
