[2024-06-18T15:45:04.687+0545] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-18T15:45:04.712+0545] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Backup_Database.send_mail scheduled__2024-06-18T09:50:00+00:00 [queued]>
[2024-06-18T15:45:04.720+0545] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Backup_Database.send_mail scheduled__2024-06-18T09:50:00+00:00 [queued]>
[2024-06-18T15:45:04.720+0545] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-18T15:45:04.775+0545] {taskinstance.py:2330} INFO - Executing <Task(EmailOperator): send_mail> on 2024-06-18 09:50:00+00:00
[2024-06-18T15:45:04.778+0545] {standard_task_runner.py:63} INFO - Started process 22709 to run task
[2024-06-18T15:45:04.782+0545] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Backup_Database', 'send_mail', 'scheduled__2024-06-18T09:50:00+00:00', '--job-id', '88', '--raw', '--subdir', 'DAGS_FOLDER/basic_dag.py', '--cfg-path', '/tmp/tmprbbzijnz']
[2024-06-18T15:45:04.783+0545] {standard_task_runner.py:91} INFO - Job 88: Subtask send_mail
[2024-06-18T15:45:04.941+0545] {task_command.py:426} INFO - Running <TaskInstance: Backup_Database.send_mail scheduled__2024-06-18T09:50:00+00:00 [running]> on host manisha-Inspiron-3580
[2024-06-18T15:45:05.200+0545] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='manisha' AIRFLOW_CTX_DAG_ID='Backup_Database' AIRFLOW_CTX_TASK_ID='send_mail' AIRFLOW_CTX_EXECUTION_DATE='2024-06-18T09:50:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-18T09:50:00+00:00'
[2024-06-18T15:45:05.202+0545] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-18T15:45:05.239+0545] {logging_mixin.py:188} WARNING - /home/manisha/airflow_env/lib/python3.10/site-packages/airflow/utils/email.py:154 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2024-06-18T15:45:05.240+0545] {configuration.py:1050} WARNING - section/key [smtp/smtp_user] not found in config
[2024-06-18T15:45:05.240+0545] {email.py:271} INFO - Email alerting: attempt 1
[2024-06-18T15:45:05.256+0545] {email.py:282} INFO - Sent an alert email to ['manishakhadka228@gmail.com']
[2024-06-18T15:45:05.382+0545] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-18T15:45:05.422+0545] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Backup_Database, task_id=send_mail, run_id=scheduled__2024-06-18T09:50:00+00:00, execution_date=20240618T095000, start_date=20240618T100004, end_date=20240618T100005
[2024-06-18T15:45:05.517+0545] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-18T15:45:05.571+0545] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-18T15:45:05.572+0545] {local_task_job_runner.py:222} INFO - ::endgroup::
