[2024-06-18T14:34:04.950+0545] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-18T14:34:04.991+0545] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Backup_Database.send_mail manual__2024-06-18T08:47:53.502392+00:00 [queued]>
[2024-06-18T14:34:05.005+0545] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Backup_Database.send_mail manual__2024-06-18T08:47:53.502392+00:00 [queued]>
[2024-06-18T14:34:05.005+0545] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-18T14:34:05.192+0545] {taskinstance.py:2330} INFO - Executing <Task(EmailOperator): send_mail> on 2024-06-18 08:47:53.502392+00:00
[2024-06-18T14:34:05.201+0545] {standard_task_runner.py:63} INFO - Started process 18686 to run task
[2024-06-18T14:34:05.210+0545] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Backup_Database', 'send_mail', 'manual__2024-06-18T08:47:53.502392+00:00', '--job-id', '64', '--raw', '--subdir', 'DAGS_FOLDER/basic_dag.py', '--cfg-path', '/tmp/tmpmxl0ihmk']
[2024-06-18T14:34:05.216+0545] {standard_task_runner.py:91} INFO - Job 64: Subtask send_mail
[2024-06-18T14:34:05.440+0545] {task_command.py:426} INFO - Running <TaskInstance: Backup_Database.send_mail manual__2024-06-18T08:47:53.502392+00:00 [running]> on host manisha-Inspiron-3580
[2024-06-18T14:34:05.974+0545] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='manisha' AIRFLOW_CTX_DAG_ID='Backup_Database' AIRFLOW_CTX_TASK_ID='send_mail' AIRFLOW_CTX_EXECUTION_DATE='2024-06-18T08:47:53.502392+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-18T08:47:53.502392+00:00'
[2024-06-18T14:34:05.974+0545] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-18T14:34:06.014+0545] {logging_mixin.py:188} WARNING - /home/manisha/airflow_env/lib/python3.10/site-packages/airflow/utils/email.py:154 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2024-06-18T14:34:06.015+0545] {configuration.py:1050} WARNING - section/key [smtp/smtp_user] not found in config
[2024-06-18T14:34:06.015+0545] {email.py:271} INFO - Email alerting: attempt 1
[2024-06-18T14:34:06.021+0545] {email.py:282} INFO - Sent an alert email to ['manishakhadka228@gmail.com']
[2024-06-18T14:34:06.128+0545] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-18T14:34:06.164+0545] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Backup_Database, task_id=send_mail, run_id=manual__2024-06-18T08:47:53.502392+00:00, execution_date=20240618T084753, start_date=20240618T084904, end_date=20240618T084906
[2024-06-18T14:34:06.308+0545] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-18T14:34:06.359+0545] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-18T14:34:06.360+0545] {local_task_job_runner.py:222} INFO - ::endgroup::
